name: Build and Publish to npm

on:
  push:
    branches:
      - main

# بنضيف الـ Variable هنا عشان نتخلص من الـ Warning بتاع Node.js تماماً
env:
  FORCE_JAVASCRIPT_ACTIONS_TO_NODE24: true

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      # Checkout the source code from the repository
      - name: Checkout code
        uses: actions/checkout@v4

      # Setup Node.js environment with specified version and package registry config
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          registry-url: 'https://registry.npmjs.org'

      # Install exact dependencies matching package-lock.json
      - name: Install dependencies
        run: npm ci

      # Build the specific library 'auth-api-kp'
      - name: Build library
        run: npx ng build auth-api-kp --configuration production

      # Publish the build artifact to npm using the Classic NPM_TOKEN
      # غيرنا الـ Version احتياطياً لـ 0.1.12 لضمان الرفع النظيف بعد الـ Fail السابق
      - name: Publish Package to npm
        run: |
          if [ -d "dist/@karimprime/auth-api-kp" ]; then
            cd dist/@karimprime/auth-api-kp
          else
            cd dist/auth-api-kp
          fi
          npm publish --access public
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
